@isTest
public class ReOpenDataTest {
  /*  @isTest
    public static void ReopenDataMethod(){
        Case cs = new Case();
        cs.Status ='Open';
        cs.SuppliedEmail ='arpit@gmail.com';
        cs.Bucket__c ='Delivered';
        cs.Case_Re_Open_Resolution_Reason__c ='Left/Right Side not working';
        cs.Origin ='Email';
        cs.Email__c ='arpit@gmail.com';
        insert cs;
        
        cs.Reopen_Count_New__c = 1;
        cs.Bucket__c ='Re Open';
        update cs;
        
        BucketData__c bucketData = new BucketData__c();
        bucketData.CaseId__c =cs.Id;
        bucketData.Re_Open_Resolution_Reason1__c =cs.Case_Re_Open_Resolution_Reason__c;
        bucketData.total_ReOpen__c =cs.Reopen_Count_New__c;
        insert bucketData;
        
        cs.Bucket__c ='Re Open';
        cs.Reopen_Count_New__c = 2;
        update cs;
        
        test.startTest();
        ReOpenData.NewReOpenDataMethod(cs.Id);   
        test.stopTest();
    }
    @isTest
    public static void ReopenDataMethod2(){
        Case cs = new Case();
        cs.Status ='Open';
        cs.SuppliedEmail ='arpit@gmail.com';
        cs.Bucket__c ='Delivered';
        cs.Case_Re_Open_Resolution_Reason__c ='Left/Right Side not working';
        cs.Origin ='Email';
        cs.Email__c ='arpit@gmail.com';
        insert cs;
        cs.Reopen_Count_New__c = 3;
        cs.Bucket__c ='Re Open';
        update cs;
        
        BucketData__c bucketData = new BucketData__c();
        bucketData.CaseId__c =cs.Id;
        bucketData.Re_Open_Resolution_Reason2__c =cs.Case_Re_Open_Resolution_Reason__c;
        bucketData.Re_Open_Resolution_Reason1__c =cs.Case_Re_Open_Resolution_Reason__c;
        bucketData.Re_Open_Resolution_Reason3__c =cs.Case_Re_Open_Resolution_Reason__c;
        bucketData.total_ReOpen__c =cs.Reopen_Count_New__c;
        insert bucketData;
        
        cs.Bucket__c ='Re Open';
        cs.Reopen_Count_New__c = 3;
        update cs;
        test.startTest();
        ReOpenData.NewReOpenDataMethod(cs.Id);   
        test.stopTest();
    }
    */
    
    
}